### ISSUE TITLE
creating survey for Solution3

### ISSUE THREAD

**Issue by jordy-jose** [jordy-jose/CSC_510_group_d#87]
create survey for evaluating Solution3

**Comment by stutinanda** [comment]
Created initial survey questions for solution3.

**Comment by stutinanda** [comment]
@Angelyn Please review the questions and let me know if they need any revisions

**Comment by Angelyn** [comment]
I have read the questions. Looks good. We can send them out

**Comment by stutinanda** [comment]
Thanks! closing this issue.
